-- QR-2A funcional autosuficiente. Fixtures temporales; ejecutar en una sola sesion.
BEGIN;
CREATE TEMP TABLE qr2a_results (orden integer PRIMARY KEY, prueba text NOT NULL, resultado text NOT NULL, detalle text NOT NULL) ON COMMIT DROP;
DO $test$
DECLARE
 master_auth uuid := '397bc597-6e61-4447-a222-dcdb55051f7b'; admin_auth uuid := 'a3b47ae0-2824-4763-941c-4b38d9785994';
 operator_auth uuid := 'd29465aa-678c-4f00-87fb-cdaed8ea55d9'; consulta_auth uuid := 'f85e972f-8c72-4556-a302-10b419ee5a7e';
 no_access_auth uuid := '8174dd8b-ab48-44d4-83b0-12deb74ee1ac'; test_account integer := 2; test_event integer := 1;
 invitation_a integer := 1; invitation_b integer := 2; invitation_c integer := 3;
 response jsonb; admin_response jsonb; result_code text;
BEGIN
 ASSERT (SELECT count(*)=3 FROM public.evp_inv_invitacion WHERE inv_cuenta_id=test_account AND inv_evento_id=test_event AND inv_estado='Activo' AND inv_invitacion_id IN(invitation_a,invitation_b,invitation_c)), 'CONFIG: invitaciones 1,2,3 activas en 2/1 requeridas';
 ASSERT NOT EXISTS (SELECT 1 FROM public.evp_iqr_invitacion_qr WHERE iqr_cuenta_id=test_account AND iqr_evento_id=test_event AND (iqr_invitacion_id IN(invitation_a,invitation_b,invitation_c) OR iqr_codigo IN('Q2A1','Q2R1','Q2R2','Q2V1','ZZZZ'))), 'CONFIG: QR historico interfiere';
 ASSERT EXISTS (SELECT 1 FROM public.evp_usr_usuario u JOIN public.evp_ucu_usuario_cuenta r ON r.ucu_usuario_id=u.usr_usuario_id WHERE u.usr_usuario_auth_uuid=admin_auth AND u.usr_estado='Activo' AND r.ucu_cuenta_id=test_account AND r.ucu_estado='Activo' AND r.ucu_rol='Administrador'), 'CONFIG ADMIN invalida';
 ASSERT EXISTS (SELECT 1 FROM public.evp_usr_usuario u JOIN public.evp_ucu_usuario_cuenta r ON r.ucu_usuario_id=u.usr_usuario_id JOIN public.evp_uev_usuario_evento e ON e.uev_usuario_id=u.usr_usuario_id AND e.uev_cuenta_id=test_account AND e.uev_evento_id=test_event WHERE u.usr_usuario_auth_uuid=operator_auth AND r.ucu_rol='Operador' AND r.ucu_estado='Activo' AND e.uev_estado='Activo'), 'CONFIG OPERADOR UEV invalida';
 ASSERT EXISTS (SELECT 1 FROM public.evp_usr_usuario u JOIN public.evp_ucu_usuario_cuenta r ON r.ucu_usuario_id=u.usr_usuario_id JOIN public.evp_uev_usuario_evento e ON e.uev_usuario_id=u.usr_usuario_id AND e.uev_cuenta_id=test_account AND e.uev_evento_id=test_event WHERE u.usr_usuario_auth_uuid=consulta_auth AND r.ucu_rol='Consulta' AND r.ucu_estado='Activo' AND e.uev_estado='Activo'), 'CONFIG CONSULTA UEV invalida';
 ASSERT NOT EXISTS (SELECT 1 FROM public.evp_uev_usuario_evento e JOIN public.evp_usr_usuario u ON u.usr_usuario_id=e.uev_usuario_id WHERE u.usr_usuario_auth_uuid=no_access_auth AND e.uev_cuenta_id=test_account AND e.uev_evento_id=test_event AND e.uev_estado='Activo'), 'CONFIG NO_ACCESS tiene UEV activa 2/1';
 UPDATE public.evp_eve_evento SET eve_fase_evento='En_proceso', eve_fecha_hora_inicio=pg_catalog.now()-pg_catalog.make_interval(hours=>1), eve_fecha_hora_fin=pg_catalog.now()+pg_catalog.make_interval(hours=>3) WHERE eve_cuenta_id=test_account AND eve_evento_id=test_event;
 ASSERT EXISTS (SELECT 1 FROM public.evp_eve_evento e WHERE e.eve_cuenta_id=test_account AND e.eve_evento_id=test_event
   AND e.eve_estado='Activo' AND e.eve_fase_evento='En_proceso' AND e.eve_fecha_hora_inicio<e.eve_fecha_hora_fin
   AND pg_catalog.now() BETWEEN e.eve_fecha_hora_inicio-pg_catalog.make_interval(hours=>8) AND e.eve_fecha_hora_fin+pg_catalog.make_interval(hours=>4)),
   'SETUP EVENT_WINDOW esperaba evento Activo/En_proceso y ventana QR vigente';
 PERFORM pg_catalog.set_config('request.jwt.claim.sub',master_auth::text,true);
 admin_response:=public.evp_admin_crear_qr_invitacion(test_account,test_event,invitation_a,'Q2A1'); ASSERT admin_response->>'codigo_resultado'='QR_CREATED','SETUP Q2A1 esperado QR_CREATED, obtuvo '||coalesce(admin_response->>'codigo_resultado','NULL');
 admin_response:=public.evp_admin_crear_qr_invitacion(test_account,test_event,invitation_b,'Q2R1'); ASSERT admin_response->>'codigo_resultado'='QR_CREATED','SETUP Q2R1 esperado QR_CREATED';
 admin_response:=public.evp_admin_regenerar_qr_invitacion(test_account,test_event,invitation_b,'Q2R2'); ASSERT admin_response->>'codigo_resultado'='QR_REGENERATED','SETUP Q2R2 esperado QR_REGENERATED';
 admin_response:=public.evp_admin_crear_qr_invitacion(test_account,test_event,invitation_c,'Q2V1'); ASSERT admin_response->>'codigo_resultado'='QR_CREATED','SETUP Q2V1 esperado QR_CREATED';
 response:=public.evp_oper_resolver_invitacion_qr(test_account,test_event,'q2a1'); ASSERT response->>'codigo_resultado'='QR_RESOLVED' AND response->>'invitacion_id'=invitation_a::text,'MASTER_LOWER esperaba QR_RESOLVED invitacion 1, obtuvo '||coalesce(response->>'codigo_resultado','NULL'); INSERT INTO qr2a_results VALUES(10,'MASTER_LOWER','PASS','Q2A1 resuelve invitation 1');
 response:=public.evp_oper_resolver_invitacion_qr(test_account,test_event,'  q2a1  '); ASSERT response->>'codigo_resultado'='QR_RESOLVED','MASTER_TRIM esperaba QR_RESOLVED, obtuvo '||coalesce(response->>'codigo_resultado','NULL'); INSERT INTO qr2a_results VALUES(20,'MASTER_TRIM','PASS','Normaliza espacios');
 PERFORM pg_catalog.set_config('request.jwt.claim.sub',admin_auth::text,true); response:=public.evp_oper_resolver_invitacion_qr(test_account,test_event,'Q2A1'); ASSERT response->>'codigo_resultado'='QR_RESOLVED','ADMIN esperaba QR_RESOLVED, obtuvo '||coalesce(response->>'codigo_resultado','NULL'); INSERT INTO qr2a_results VALUES(30,'ADMIN','PASS','Administrador autorizado');
 PERFORM pg_catalog.set_config('request.jwt.claim.sub',operator_auth::text,true); response:=public.evp_oper_resolver_invitacion_qr(test_account,test_event,'Q2A1'); ASSERT response->>'codigo_resultado'='QR_RESOLVED','OPERATOR esperaba QR_RESOLVED, obtuvo '||coalesce(response->>'codigo_resultado','NULL'); INSERT INTO qr2a_results VALUES(40,'OPERATOR','PASS','Operador UEV autorizado');
 PERFORM pg_catalog.set_config('request.jwt.claim.sub',consulta_auth::text,true); response:=public.evp_oper_resolver_invitacion_qr(test_account,test_event,'Q2A1'); ASSERT response->>'codigo_resultado'='QR_RESOLVED','CONSULTA esperaba QR_RESOLVED, obtuvo '||coalesce(response->>'codigo_resultado','NULL'); INSERT INTO qr2a_results VALUES(50,'CONSULTA','PASS','Consulta UEV solo lectura');
 PERFORM pg_catalog.set_config('request.jwt.claim.sub',no_access_auth::text,true); response:=public.evp_oper_resolver_invitacion_qr(test_account,test_event,'Q2A1'); ASSERT response->>'codigo_resultado'='QR_NOT_ALLOWED','NO_ACCESS esperaba QR_NOT_ALLOWED, obtuvo '||coalesce(response->>'codigo_resultado','NULL'); INSERT INTO qr2a_results VALUES(60,'NO_ACCESS','PASS','Sin UEV 2/1 rechazado');
 PERFORM pg_catalog.set_config('request.jwt.claim.sub',master_auth::text,true);
 response:=public.evp_oper_resolver_invitacion_qr(test_account,test_event,'Q-21'); ASSERT response->>'codigo_resultado'='QR_INVALID_FORMAT','INVALID_FORMAT esperaba QR_INVALID_FORMAT'; INSERT INTO qr2a_results VALUES(70,'INVALID_FORMAT','PASS','Formato rechazado');
 response:=public.evp_oper_resolver_invitacion_qr(test_account,test_event,'ZZZZ'); ASSERT response->>'codigo_resultado'='QR_NOT_FOUND','NOT_FOUND esperaba QR_NOT_FOUND'; INSERT INTO qr2a_results VALUES(80,'NOT_FOUND','PASS','Codigo libre no resuelve');
 response:=public.evp_oper_resolver_invitacion_qr(test_account,test_event,'Q2R1'); ASSERT response->>'codigo_resultado'='QR_REVOKED','REVOKED esperaba QR_REVOKED, obtuvo '||coalesce(response->>'codigo_resultado','NULL'); INSERT INTO qr2a_results VALUES(90,'REVOKED','PASS','QR revocado rechazado');
 response:=public.evp_oper_resolver_invitacion_qr(3,1,'Q2A1'); ASSERT response->>'codigo_resultado' IN('QR_NOT_FOUND','QR_NOT_AVAILABLE'),'CROSS_ACCOUNT rechazo esperado'; INSERT INTO qr2a_results VALUES(100,'CROSS_ACCOUNT','PASS','Sin fuga 2/1');
 response:=public.evp_oper_resolver_invitacion_qr(2,8,'Q2A1'); ASSERT response->>'codigo_resultado' IN('QR_NOT_FOUND','QR_NOT_AVAILABLE'),'CROSS_EVENT rechazo esperado'; INSERT INTO qr2a_results VALUES(110,'CROSS_EVENT','PASS','Sin fuga evento 1');
 UPDATE public.evp_iqr_invitacion_qr SET iqr_valido_hasta=pg_catalog.now()-pg_catalog.make_interval(mins=>1) WHERE iqr_cuenta_id=test_account AND iqr_evento_id=test_event AND iqr_codigo='Q2V1'; response:=public.evp_oper_resolver_invitacion_qr(test_account,test_event,'Q2V1'); ASSERT response->>'codigo_resultado'='QR_NOT_AVAILABLE','OUTSIDE_VALIDITY esperaba QR_NOT_AVAILABLE'; INSERT INTO qr2a_results VALUES(120,'OUTSIDE_VALIDITY','PASS','QR temporal vencido');
 UPDATE public.evp_inv_invitacion SET inv_estado='Suspendido' WHERE inv_cuenta_id=test_account AND inv_evento_id=test_event AND inv_invitacion_id=invitation_a; response:=public.evp_oper_resolver_invitacion_qr(test_account,test_event,'Q2A1'); ASSERT response->>'codigo_resultado'='QR_NOT_AVAILABLE','INVITATION_INACTIVE esperaba QR_NOT_AVAILABLE'; INSERT INTO qr2a_results VALUES(130,'INVITATION_INACTIVE','PASS','Invitacion temporalmente suspendida');
 UPDATE public.evp_inv_invitacion SET inv_estado='Activo' WHERE inv_cuenta_id=test_account AND inv_evento_id=test_event AND inv_invitacion_id=invitation_a;
 UPDATE public.evp_eve_evento SET eve_fase_evento='Post_evento' WHERE eve_cuenta_id=test_account AND eve_evento_id=test_event; response:=public.evp_oper_resolver_invitacion_qr(test_account,test_event,'Q2A1'); ASSERT response->>'codigo_resultado'='QR_NOT_AVAILABLE','INVALID_PHASE esperaba QR_NOT_AVAILABLE'; INSERT INTO qr2a_results VALUES(140,'INVALID_PHASE','PASS','Post_evento rechazado');
 ASSERT (SELECT count(*)=14 FROM qr2a_results); INSERT INTO qr2a_results VALUES(150,'SUMMARY','PASS','14/14 casos superados; ROLLBACK restaura todo');
END $test$;
SELECT prueba,resultado,detalle FROM qr2a_results ORDER BY orden;
ROLLBACK;
