-- QR-2B functional. Ejecutar en una sola sesion; ante fallo ejecute ROLLBACK.
BEGIN;
CREATE TEMP TABLE arrival_results (orden integer PRIMARY KEY, prueba text NOT NULL, resultado text NOT NULL, detalle text NOT NULL) ON COMMIT DROP;
DO $test$
DECLARE
  master_auth uuid := '397bc597-6e61-4447-a222-dcdb55051f7b'; admin_auth uuid := 'a3b47ae0-2824-4763-941c-4b38d9785994'; operator_auth uuid := 'd29465aa-678c-4f00-87fb-cdaed8ea55d9'; consulta_auth uuid := 'f85e972f-8c72-4556-a302-10b419ee5a7e'; no_access_auth uuid := '8174dd8b-ab48-44d4-83b0-12deb74ee1ac';
  test_account integer := 2; test_event integer := 1; test_invitation integer := 3; guest_a integer := 1; guest_b integer := 2; guest_c integer := 3; foreign_invitation integer := 1; foreign_guest integer := 4;
  foreign_account integer := 3; foreign_event integer := 1; other_event integer := 8;
  r jsonb; v_master_usuario uuid; v_fecha_b timestamptz; v_fecha_c timestamptz; v_actor_b uuid; v_actor_c uuid; v_before_b boolean; v_before_c boolean;
BEGIN
  ASSERT EXISTS (SELECT 1 FROM public.evp_cta_cuenta WHERE cta_cuenta_id=test_account AND cta_estado='Activo'), 'CONFIG: cuenta 2 debe estar Activa';
  ASSERT EXISTS (SELECT 1 FROM public.evp_eve_evento WHERE eve_cuenta_id=test_account AND eve_evento_id=test_event AND eve_estado='Activo'), 'CONFIG: evento 2/1 debe estar Activo';
  ASSERT EXISTS (SELECT 1 FROM public.evp_inv_invitacion WHERE inv_cuenta_id=test_account AND inv_evento_id=test_event AND inv_invitacion_id=test_invitation AND inv_estado='Activo'), 'CONFIG: invitacion 2/1/3 debe estar Activa';
  ASSERT (SELECT count(*)=3 FROM public.evp_ivt_invitado WHERE ivt_cuenta_id=2 AND ivt_evento_id=1 AND ivt_invitacion_id=3 AND ivt_estado='Activo' AND ivt_invitado_id IN(1,2,3)), 'CONFIG: invitados 1,2,3 activos en 2/1/3 requeridos';
  ASSERT EXISTS (SELECT 1 FROM public.evp_ivt_invitado WHERE ivt_cuenta_id=2 AND ivt_evento_id=1 AND ivt_invitacion_id=1 AND ivt_invitado_id=4 AND ivt_estado='Activo') AND NOT EXISTS (SELECT 1 FROM public.evp_ivt_invitado WHERE ivt_cuenta_id=2 AND ivt_evento_id=1 AND ivt_invitacion_id=3 AND ivt_invitado_id=4), 'CONFIG: guest 4 debe pertenecer solo a 2/1/1';
  SELECT usr_usuario_id INTO v_master_usuario FROM public.evp_usr_usuario WHERE usr_usuario_auth_uuid=master_auth AND usr_estado='Activo' AND usr_es_usuario_master; ASSERT v_master_usuario IS NOT NULL, 'CONFIG: Master activo invalido';
  ASSERT EXISTS (SELECT 1 FROM public.evp_usr_usuario u JOIN public.evp_ucu_usuario_cuenta x ON x.ucu_usuario_id=u.usr_usuario_id WHERE u.usr_usuario_auth_uuid=admin_auth AND u.usr_estado='Activo' AND x.ucu_cuenta_id=2 AND x.ucu_estado='Activo' AND x.ucu_rol='Administrador'), 'CONFIG: Admin sin UCU Administrador activa en 2';
  ASSERT EXISTS (SELECT 1 FROM public.evp_usr_usuario u JOIN public.evp_ucu_usuario_cuenta x ON x.ucu_usuario_id=u.usr_usuario_id JOIN public.evp_uev_usuario_evento y ON y.uev_usuario_id=u.usr_usuario_id AND y.uev_cuenta_id=2 AND y.uev_evento_id=1 WHERE u.usr_usuario_auth_uuid=operator_auth AND u.usr_estado='Activo' AND x.ucu_estado='Activo' AND x.ucu_rol='Operador' AND y.uev_estado='Activo'), 'CONFIG: Operador sin UCU/UEV activa 2/1';
  ASSERT EXISTS (SELECT 1 FROM public.evp_usr_usuario u JOIN public.evp_ucu_usuario_cuenta x ON x.ucu_usuario_id=u.usr_usuario_id JOIN public.evp_uev_usuario_evento y ON y.uev_usuario_id=u.usr_usuario_id AND y.uev_cuenta_id=2 AND y.uev_evento_id=1 WHERE u.usr_usuario_auth_uuid=consulta_auth AND u.usr_estado='Activo' AND x.ucu_estado='Activo' AND x.ucu_rol='Consulta' AND y.uev_estado='Activo'), 'CONFIG: Consulta sin UCU/UEV activa 2/1';
  ASSERT NOT EXISTS (SELECT 1 FROM public.evp_usr_usuario u JOIN public.evp_uev_usuario_evento y ON y.uev_usuario_id=u.usr_usuario_id WHERE u.usr_usuario_auth_uuid=no_access_auth AND y.uev_cuenta_id=2 AND y.uev_evento_id=1 AND y.uev_estado='Activo'), 'CONFIG: usuario sin acceso conserva UEV activa 2/1';
  UPDATE public.evp_eve_evento SET eve_fase_evento='En_proceso',eve_fecha_hora_inicio=pg_catalog.now()-interval '1 hour',eve_fecha_hora_fin=pg_catalog.now()+interval '3 hours' WHERE eve_cuenta_id=2 AND eve_evento_id=1;
  ASSERT EXISTS (SELECT 1 FROM public.evp_eve_evento WHERE eve_cuenta_id=2 AND eve_evento_id=1 AND eve_estado='Activo' AND eve_fase_evento='En_proceso' AND eve_fecha_hora_inicio<eve_fecha_hora_fin AND pg_catalog.now() BETWEEN eve_fecha_hora_inicio-interval '8 hours' AND eve_fecha_hora_fin+interval '4 hours'), 'SETUP EVENT: 2/1 no quedo operativo';
  UPDATE public.evp_ivt_invitado SET ivt_llegada_confirmada=false,ivt_fecha_hora_conf_llegada=NULL,ivt_usuario_conf_llegada=NULL WHERE ivt_cuenta_id=2 AND ivt_evento_id=1 AND ivt_invitacion_id=3 AND ivt_invitado_id IN(1,2,3);
  ASSERT NOT EXISTS (SELECT 1 FROM public.evp_ivt_invitado WHERE ivt_cuenta_id=2 AND ivt_evento_id=1 AND ivt_invitacion_id=3 AND ivt_invitado_id IN(1,2,3) AND (ivt_llegada_confirmada OR ivt_fecha_hora_conf_llegada IS NOT NULL OR ivt_usuario_conf_llegada IS NOT NULL)), 'SETUP GUESTS: 1,2,3 deben quedar pendientes';

  PERFORM pg_catalog.set_config('request.jwt.claim.sub',master_auth::text,true);
  r:=public.evp_oper_obtener_grupo_invitacion(2,1,3); ASSERT r->>'codigo_resultado'='ARRIVAL_GROUP_LOADED' AND r->>'invitacion_id'='3' AND pg_catalog.jsonb_array_length(r->'invitados')=3 AND NOT EXISTS(SELECT 1 FROM pg_catalog.jsonb_array_elements(r->'invitados') x WHERE (x->>'invitado_id')::integer NOT IN(1,2,3) OR (x->>'llegada_confirmada')::boolean), 'A MASTER_GROUP esperaba 1,2,3 pendientes; obtuvo '||r::text; INSERT INTO arrival_results VALUES(10,'A_MASTER_GROUP','PASS','Master obtiene solo 1,2,3 pendientes');
  r:=public.evp_oper_obtener_grupo_invitacion(2,1,1); ASSERT r->>'codigo_resultado'='ARRIVAL_GROUP_LOADED' AND r->>'invitacion_id'='1','B INVITATION_ISOLATION obtuvo '||r::text; INSERT INTO arrival_results VALUES(20,'B_INVITATION_ISOLATION','PASS','Consulta exacta no mezcla invitaciones');
  r:=public.evp_oper_confirmar_llegadas_invitacion(2,1,3,ARRAY[1]); ASSERT r->>'codigo_resultado'='ARRIVAL_CONFIRMED' AND (SELECT ivt_llegada_confirmada FROM public.evp_ivt_invitado WHERE ivt_cuenta_id=2 AND ivt_evento_id=1 AND ivt_invitacion_id=3 AND ivt_invitado_id=1) AND NOT EXISTS(SELECT 1 FROM public.evp_ivt_invitado WHERE ivt_cuenta_id=2 AND ivt_evento_id=1 AND ivt_invitacion_id=3 AND ivt_invitado_id IN(2,3) AND ivt_llegada_confirmada),'C PARTIAL esperaba solo guest_a; obtuvo '||r::text; INSERT INTO arrival_results VALUES(30,'C_MASTER_PARTIAL','PASS','Solo guest_a confirmado');
  SELECT ivt_llegada_confirmada INTO v_before_b FROM public.evp_ivt_invitado WHERE ivt_cuenta_id=2 AND ivt_evento_id=1 AND ivt_invitacion_id=3 AND ivt_invitado_id=2; r:=public.evp_oper_confirmar_llegadas_invitacion(2,1,3,ARRAY[2,4]); ASSERT r->>'codigo_resultado'='ARRIVAL_INVALID_SELECTION' AND (SELECT ivt_llegada_confirmada=v_before_b FROM public.evp_ivt_invitado WHERE ivt_cuenta_id=2 AND ivt_evento_id=1 AND ivt_invitacion_id=3 AND ivt_invitado_id=2),'D CROSS_INVITATION altero lote; obtuvo '||r::text; INSERT INTO arrival_results VALUES(40,'D_CROSS_INVITATION_ATOMIC','PASS','Guest 4 rechaza todo el lote');
  r:=public.evp_oper_confirmar_llegadas_invitacion(2,1,3,ARRAY[]::integer[]); ASSERT r->>'codigo_resultado'='ARRIVAL_EMPTY_SELECTION','E EMPTY obtuvo '||r::text; r:=public.evp_oper_confirmar_llegadas_invitacion(2,1,3,ARRAY[2,2]); ASSERT r->>'codigo_resultado'='ARRIVAL_INVALID_SELECTION','E DUPLICATE obtuvo '||r::text; INSERT INTO arrival_results VALUES(50,'E_EMPTY_DUPLICATE','PASS','Lista vacia y duplicada no escriben');
  r:=public.evp_oper_confirmar_llegadas_invitacion(2,1,3,ARRAY[1,2]); ASSERT r->>'codigo_resultado'='ARRIVAL_ALREADY_CONFIRMED' AND NOT (SELECT ivt_llegada_confirmada FROM public.evp_ivt_invitado WHERE ivt_cuenta_id=2 AND ivt_evento_id=1 AND ivt_invitacion_id=3 AND ivt_invitado_id=2),'F ALREADY no debe confirmar guest_b; obtuvo '||r::text; INSERT INTO arrival_results VALUES(60,'F_ALREADY_CONFIRMED','PASS','Ya confirmado rechaza lote completo');
  r:=public.evp_oper_confirmar_llegadas_invitacion(2,1,3,ARRAY[2,3]); ASSERT r->>'codigo_resultado'='ARRIVAL_CONFIRMED','G MASTER_BATCH obtuvo '||r::text; SELECT ivt_fecha_hora_conf_llegada,ivt_usuario_conf_llegada INTO v_fecha_b,v_actor_b FROM public.evp_ivt_invitado WHERE ivt_cuenta_id=2 AND ivt_evento_id=1 AND ivt_invitacion_id=3 AND ivt_invitado_id=2; SELECT ivt_fecha_hora_conf_llegada,ivt_usuario_conf_llegada INTO v_fecha_c,v_actor_c FROM public.evp_ivt_invitado WHERE ivt_cuenta_id=2 AND ivt_evento_id=1 AND ivt_invitacion_id=3 AND ivt_invitado_id=3; ASSERT v_fecha_b=v_fecha_c AND v_fecha_b=(r->>'fecha_hora_confirmacion')::timestamptz AND v_actor_b=v_master_usuario AND v_actor_c=v_master_usuario AND r->>'usuario_confirmacion'=v_master_usuario::text,'G BATCH_AUDIT timestamp/actor incorrectos; obtuvo '||r::text; INSERT INTO arrival_results VALUES(70,'G_MASTER_BATCH_AUDIT','PASS','2,3 comparten timestamp y usr_usuario_id Master');

  UPDATE public.evp_ivt_invitado SET ivt_llegada_confirmada=false,ivt_fecha_hora_conf_llegada=NULL,ivt_usuario_conf_llegada=NULL WHERE ivt_cuenta_id=2 AND ivt_evento_id=1 AND ivt_invitacion_id=3 AND ivt_invitado_id IN(1,2,3);
  PERFORM pg_catalog.set_config('request.jwt.claim.sub',admin_auth::text,true); r:=public.evp_oper_obtener_grupo_invitacion(2,1,3); ASSERT r->>'codigo_resultado'='ARRIVAL_GROUP_LOADED','H ADMIN_READ obtuvo '||r::text; r:=public.evp_oper_confirmar_llegadas_invitacion(2,1,3,ARRAY[1,2]); ASSERT r->>'codigo_resultado'='ARRIVAL_CONFIRMED','H ADMIN_WRITE obtuvo '||r::text; INSERT INTO arrival_results VALUES(80,'H_ADMIN_READ_WRITE','PASS','Administrador consulta y confirma');
  UPDATE public.evp_ivt_invitado SET ivt_llegada_confirmada=false,ivt_fecha_hora_conf_llegada=NULL,ivt_usuario_conf_llegada=NULL WHERE ivt_cuenta_id=2 AND ivt_evento_id=1 AND ivt_invitacion_id=3 AND ivt_invitado_id IN(1,2,3);
  PERFORM pg_catalog.set_config('request.jwt.claim.sub',operator_auth::text,true); r:=public.evp_oper_obtener_grupo_invitacion(2,1,3); ASSERT r->>'codigo_resultado'='ARRIVAL_GROUP_LOADED','I OPERATOR_READ obtuvo '||r::text; r:=public.evp_oper_confirmar_llegadas_invitacion(2,1,3,ARRAY[1,2]); ASSERT r->>'codigo_resultado'='ARRIVAL_CONFIRMED','I OPERATOR_WRITE obtuvo '||r::text; INSERT INTO arrival_results VALUES(90,'I_OPERATOR_READ_WRITE','PASS','Operador UEV consulta y confirma');
  PERFORM pg_catalog.set_config('request.jwt.claim.sub',consulta_auth::text,true); r:=public.evp_oper_obtener_grupo_invitacion(2,1,3); ASSERT r->>'codigo_resultado'='ARRIVAL_GROUP_LOADED','J CONSULTA_READ obtuvo '||r::text; r:=public.evp_oper_confirmar_llegadas_invitacion(2,1,3,ARRAY[3]); ASSERT r->>'codigo_resultado'='ARRIVAL_NOT_ALLOWED','J CONSULTA_WRITE obtuvo '||r::text; INSERT INTO arrival_results VALUES(100,'J_CONSULTA','PASS','Consulta lee y no confirma');
  PERFORM pg_catalog.set_config('request.jwt.claim.sub',no_access_auth::text,true); r:=public.evp_oper_obtener_grupo_invitacion(2,1,3); ASSERT r->>'codigo_resultado'='ARRIVAL_NOT_ALLOWED','K NO_ACCESS_READ obtuvo '||r::text; r:=public.evp_oper_confirmar_llegadas_invitacion(2,1,3,ARRAY[3]); ASSERT r->>'codigo_resultado'='ARRIVAL_NOT_ALLOWED','K NO_ACCESS_WRITE obtuvo '||r::text; INSERT INTO arrival_results VALUES(110,'K_NO_ACCESS','PASS','Sin UEV 2/1 rechazado');
  SELECT ivt_llegada_confirmada INTO v_before_c FROM public.evp_ivt_invitado WHERE ivt_cuenta_id=2 AND ivt_evento_id=1 AND ivt_invitacion_id=3 AND ivt_invitado_id=3;
  PERFORM pg_catalog.set_config('request.jwt.claim.sub',admin_auth::text,true); r:=public.evp_oper_confirmar_llegadas_invitacion(foreign_account,foreign_event,3,ARRAY[3]); ASSERT r->>'ok'='false' AND r->>'codigo_resultado'='ARRIVAL_EVENT_NOT_ALLOWED' AND NOT (r ? 'invitados') AND NOT (r ? 'invitado_ids') AND (SELECT ivt_llegada_confirmada=v_before_c FROM public.evp_ivt_invitado WHERE ivt_cuenta_id=2 AND ivt_evento_id=1 AND ivt_invitacion_id=3 AND ivt_invitado_id=3),'L CROSS_ACCOUNT esperaba rechazo operativo sin escritura target; obtuvo '||r::text;
  PERFORM pg_catalog.set_config('request.jwt.claim.sub',operator_auth::text,true); r:=public.evp_oper_confirmar_llegadas_invitacion(2,other_event,3,ARRAY[3]); ASSERT r->>'ok'='false' AND r->>'codigo_resultado'='ARRIVAL_INVALID_SELECTION' AND NOT (r ? 'invitados') AND NOT (r ? 'invitado_ids') AND (SELECT ivt_llegada_confirmada=v_before_c FROM public.evp_ivt_invitado WHERE ivt_cuenta_id=2 AND ivt_evento_id=1 AND ivt_invitacion_id=3 AND ivt_invitado_id=3) AND NOT EXISTS(SELECT 1 FROM public.evp_ivt_invitado WHERE ivt_cuenta_id=2 AND ivt_evento_id=other_event AND ivt_invitacion_id=3 AND ivt_invitado_id=3 AND ivt_llegada_confirmada),'L CROSS_EVENT esperaba ARRIVAL_INVALID_SELECTION sin escrituras; obtuvo '||r::text;
  INSERT INTO arrival_results VALUES(120,'L_ACCOUNT_EVENT_ISOLATION','PASS','Cuenta y evento ajenos rechazados sin alterar target');
  PERFORM pg_catalog.set_config('request.jwt.claim.sub',master_auth::text,true); UPDATE public.evp_inv_invitacion SET inv_estado='Suspendido' WHERE inv_cuenta_id=2 AND inv_evento_id=1 AND inv_invitacion_id=3; r:=public.evp_oper_obtener_grupo_invitacion(2,1,3); ASSERT r->>'codigo_resultado'='ARRIVAL_INVITATION_NOT_FOUND','M INACTIVE_INVITATION_READ obtuvo '||r::text; r:=public.evp_oper_confirmar_llegadas_invitacion(2,1,3,ARRAY[3]); ASSERT r->>'codigo_resultado'='ARRIVAL_INVITATION_NOT_FOUND','M INACTIVE_INVITATION_WRITE obtuvo '||r::text; UPDATE public.evp_inv_invitacion SET inv_estado='Activo' WHERE inv_cuenta_id=2 AND inv_evento_id=1 AND inv_invitacion_id=3; INSERT INTO arrival_results VALUES(130,'M_INACTIVE_INVITATION','PASS','Invitacion suspendida rechazada');
  UPDATE public.evp_eve_evento SET eve_fase_evento='Post_evento' WHERE eve_cuenta_id=2 AND eve_evento_id=1; r:=public.evp_oper_obtener_grupo_invitacion(2,1,3); ASSERT r->>'codigo_resultado'='ARRIVAL_EVENT_NOT_ALLOWED','N INVALID_PHASE_READ obtuvo '||r::text; r:=public.evp_oper_confirmar_llegadas_invitacion(2,1,3,ARRAY[3]); ASSERT r->>'codigo_resultado'='ARRIVAL_EVENT_NOT_ALLOWED','N INVALID_PHASE_WRITE obtuvo '||r::text; INSERT INTO arrival_results VALUES(140,'N_INVALID_PHASE','PASS','Post_evento rechazado al final');
  ASSERT (SELECT count(*)=14 FROM arrival_results),'SUMMARY esperaba 14 grupos efectivos'; INSERT INTO arrival_results VALUES(150,'SUMMARY','PASS','14/14 grupos; ROLLBACK restaura todos los cambios');
END $test$;
SELECT prueba,resultado,detalle FROM arrival_results ORDER BY orden;
ROLLBACK;
